-- ═══════════════════════════════════════════════════════════════════
-- Log de alterações da ficha — quem mudou o quê, Mestre ou o próprio
-- jogador (pelo login dele).
--
-- Existia só um "Log de Combate" (assets/js/log_combate.js): client-side,
-- não persiste (reseta ao recarregar), e só registrava dano/cura/condição
-- feitos PELO PAINEL DO MESTRE — uma edição do jogador na própria ficha,
-- ou qualquer outro campo (nível, atributo, inventário…), não aparecia em
-- lugar nenhum.
--
-- Por que trigger e não os módulos JS registrarem: characters.* é gravado
-- por uns 10 arquivos diferentes (dbsync.js dos painéis, salvar.js/
-- recursos.js/aba_habilidades.js/aba_aliados.js/nucleo.js da ficha) — cada
-- um logando por conta própria significa lembrar de repetir a lógica em
-- todo save novo, pra sempre. Um trigger AFTER UPDATE pega TODA gravação,
-- não importa por onde ela veio, e usa auth.uid() de verdade (não o que o
-- cliente diz que é) pra saber quem fez — exatamente o "pelo login dele".
--
-- Já existia characters.updated_by (sql/018) pra saber quem fez a ÚLTIMA
-- mudança; isto aqui é o histórico, campo a campo.
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.character_changes (
  id bigint generated by default as identity primary key,
  character_id uuid not null references public.characters(id) on delete cascade,
  -- Denormalizado de characters.user_id (o DONO da ficha, não quem editou —
  -- isso é changed_by). É o que permite ao jogador escutar o Realtime com um
  -- filtro simples (user_id=eq.<meu id>), no MESMO padrão que
  -- assets/js/ficha/nucleo.js já usa pra characters — sem isso, o filtro do
  -- Postgres Changes (só igualdade numa coluna) não tem como dizer "qualquer
  -- personagem que seja meu" sem essa coluna pronta na própria linha, e o
  -- jogador teria que reassinar o canal toda vez que trocasse de PJ.
  user_id uuid not null,
  changed_by uuid,               -- auth.uid() de quem gravou; null = script admin
  por_mestre boolean not null,   -- is_mestre() no momento da gravação
  campo text not null,           -- nome da coluna (chave técnica)
  rotulo text not null,          -- rótulo em português, pra exibir direto
  valor_antes text,              -- null nos campos "blob" (ver função abaixo)
  valor_depois text,
  criado_em timestamptz not null default now()
);

-- Idempotente pra quem já rodou uma versão anterior desta migration sem a
-- coluna (ela nasceu depois, na mesma sessão de desenvolvimento).
alter table public.character_changes add column if not exists user_id uuid;
update public.character_changes cc set user_id = c.user_id
  from public.characters c where c.id = cc.character_id and cc.user_id is null;
alter table public.character_changes alter column user_id set not null;

comment on table public.character_changes is
  'Histórico de alterações em characters, uma linha por campo mudado. Preenchido só pelo trigger registrar_alteracoes_ficha() — não é gravável direto pelo cliente.';

create index if not exists idx_character_changes_char_data
  on public.character_changes(character_id, criado_em desc);
create index if not exists idx_character_changes_user
  on public.character_changes(user_id, criado_em desc);

alter table public.character_changes enable row level security;

-- Mesma visibilidade de characters: o dono ou o Mestre. Sem policy de
-- insert/update/delete pra authenticated — a única porta de entrada é o
-- trigger abaixo (roda como o dono da função, ignora RLS).
drop policy if exists character_changes_select on public.character_changes;
create policy character_changes_select on public.character_changes
  for select using (
    exists (
      select 1 from public.characters c
      where c.id = character_changes.character_id
        and (c.user_id = auth.uid() or public.is_mestre())
    )
  );

-- ─── Trigger: registra cada coluna que mudou ─────────────────────────
create or replace function public.registrar_alteracoes_ficha()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  atuando uuid := auth.uid();
  mestre boolean := public.is_mestre();
  antigo jsonb := to_jsonb(old);
  novo jsonb := to_jsonb(new);
  chave text;
  rotulo text;
  antes text;
  depois text;
  gravou boolean := false;
  -- Metadado, não conteúdo — nunca vale a pena logar.
  ignorar constant text[] := array['id','user_id','created_at','updated_at','updated_by'];
  -- Campos "blob" (jsonb complexo ou array grande): registra QUE mudou,
  -- sem tentar formatar um antes/depois legível — um dump de JSON aqui
  -- deixaria o log ilegível pro que ele serve (dizer o que aconteceu numa
  -- olhada rápida). Quem quer o detalhe fino de inventário/atributos
  -- ainda vê no histórico do próprio Supabase, se precisar.
  eh_blob constant text[] := array['atributos','slots_magia','inventario',
    'habilidades_classe','pericias','salvaguardas','recursos_usados',
    'features_personalizadas','companions','bestiario_favoritos',
    'concentracao','habilidades_favoritas','classes_secundarias'];
begin
  if atuando is null then
    -- Sem sessão autenticada (conexão direta de script/migração) — não dá
    -- pra dizer QUEM fez, e é exatamente o que este log existe pra dizer.
    return new;
  end if;

  for chave in select jsonb_object_keys(novo) loop
    if chave = any(ignorar) then continue; end if;
    if antigo -> chave is not distinct from novo -> chave then continue; end if;

    rotulo := case chave
      when 'nome' then 'Nome' when 'raca' then 'Raça' when 'classe' then 'Classe'
      when 'subclasse' then 'Subclasse' when 'nivel' then 'Nível'
      when 'origem' then 'Origem' when 'alinhamento' then 'Alinhamento'
      when 'hp_max' then 'PV máximo' when 'hp_atual' then 'PV atual'
      when 'hp_temp' then 'PV temporário' when 'ca' then 'CA'
      when 'iniciativa_bonus' then 'Bônus de iniciativa' when 'deslocamento' then 'Deslocamento'
      when 'dado_vida_atual' then 'Dado de vida' when 'condicoes' then 'Condições'
      when 'exaustao' then 'Exaustão' when 'inspiracao' then 'Inspiração'
      when 'tracos_pessoais' then 'Traços pessoais' when 'ideais' then 'Ideais'
      when 'vinculos' then 'Vínculos' when 'defeitos' then 'Defeitos'
      when 'historia' then 'História' when 'notas' then 'Notas'
      when 'imagem_url' then 'Retrato' when 'cor_destaque' then 'Cor de destaque'
      when 'morte_sucessos' then 'Sucessos de morte' when 'morte_falhas' then 'Falhas de morte'
      when 'campanha' then 'Campanha' when 'magias_preparadas' then 'Magias preparadas'
      when 'is_active' then 'Ativo na campanha' when 'xp' then 'XP'
      when 'idiomas' then 'Idiomas' when 'ferramentas' then 'Ferramentas'
      when 'tracos_raciais' then 'Traços raciais' when 'truques_conhecidos' then 'Truques conhecidos'
      when 'magias_conhecidas' then 'Magias conhecidas' when 'cd_resistencia' then 'CD de resistência'
      when 'bonus_atq_magia' then 'Bônus de ataque mágico'
      when 'caracteristicas_adicionais' then 'Características adicionais'
      when 'percepcao_passiva' then 'Percepção passiva' when 'spell_dc' then 'CD de magia'
      when 'spell_atk' then 'Ataque de magia'
      when 'atributos' then 'Atributos' when 'slots_magia' then 'Slots de magia'
      when 'inventario' then 'Inventário' when 'habilidades_classe' then 'Habilidades de classe'
      when 'pericias' then 'Perícias' when 'salvaguardas' then 'Salvaguardas'
      when 'recursos_usados' then 'Recursos' when 'features_personalizadas' then 'Características'
      when 'companions' then 'Aliados' when 'bestiario_favoritos' then 'Bestiário favorito'
      when 'concentracao' then 'Concentração' when 'habilidades_favoritas' then 'Habilidades favoritas'
      when 'classes_secundarias' then 'Multiclasse'
      else chave  -- coluna futura sem rótulo cadastrado: mostra a chave crua
                  -- em vez de esconder a mudança (o que este log promete é
                  -- "TODA mudança aparece", não "as que a gente lembrou").
    end;

    if chave = any(eh_blob) then
      antes := null; depois := null;
    elsif chave = 'condicoes' then
      antes  := (select string_agg(x, ', ') from jsonb_array_elements_text(coalesce(antigo -> chave, '[]'::jsonb)) x);
      depois := (select string_agg(x, ', ') from jsonb_array_elements_text(coalesce(novo   -> chave, '[]'::jsonb)) x);
    else
      -- Escalar (texto/número/bool): tira as aspas que to_jsonb bota em
      -- string, e corta textos longos (história, notas) pra não inchar
      -- uma linha de log com um parágrafo inteiro.
      antes  := left(trim(both '"' from (antigo -> chave)::text), 140);
      depois := left(trim(both '"' from (novo   -> chave)::text), 140);
    end if;

    insert into public.character_changes
      (character_id, user_id, changed_by, por_mestre, campo, rotulo, valor_antes, valor_depois)
    values
      (new.id, new.user_id, atuando, mestre, chave, rotulo, antes, depois);
    gravou := true;
  end loop;

  -- Poda: mantém só as últimas 200 linhas por personagem. Sem isto o log
  -- cresce pra sempre numa campanha longa; 200 dá muitas sessões de
  -- histórico sem precisar de faxina manual. Só roda quando este UPDATE
  -- realmente gravou algo, não a cada chamada do trigger.
  if gravou then
    delete from public.character_changes
    where character_id = new.id
      and id not in (
        select id from public.character_changes
        where character_id = new.id
        order by criado_em desc
        limit 200
      );
  end if;

  return new;
end;
$$;

comment on function public.registrar_alteracoes_ficha() is
  'Trigger AFTER UPDATE em characters: grava em character_changes cada coluna que mudou, com quem mudou (auth.uid()) e se foi o Mestre.';

drop trigger if exists characters_registrar_alteracoes on public.characters;
create trigger characters_registrar_alteracoes
  after update on public.characters
  for each row execute function public.registrar_alteracoes_ficha();

-- Realtime: o painel do Mestre e a ficha do jogador escutam INSERT nesta
-- tabela pra atualizar o log ao vivo (mesmo padrão de characters/
-- spell_lists em sql/004).
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'character_changes'
  ) then
    execute 'alter publication supabase_realtime add table public.character_changes';
  end if;
end $$;

-- ── Verificação ─────────────────────────────────────────────────────
select tgname from pg_trigger where tgrelid = 'public.characters'::regclass and tgname = 'characters_registrar_alteracoes';
select tablename from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'character_changes';
